# Needs SNS topic and IAM role resources added to this template
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sends notifications when COVID-19 vaccine appointments are available at certain stores in a specified region
Parameters:
  SearchRadius:
    Type: String
    Description: Search radius for stores in a specified location (in miles)
    Default: '50'
  State:
    Type: String
    Description: US State
  ZipCode:
    Type: String
    Description: US Zip Code
Resources:
  Covid19VaccineNotifier:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/LambdaCovid19
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Environment:
        Variables:
          SEARCH_RADIUS: !Ref SearchRadius
          SNS_TOPIC_ARN: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:covid-19-vaccine-notifications'
          STATE: !Ref State
          ZIP_CODE: !Ref ZipCode
