---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sends notifications when COVID-19 vaccine appointments are available at certain stores in a specified region
Parameters:
  ExcludedLocations:
    Type: CommaDelimitedList
    Description: List of locations to exclude
    Default: ''
  ScheduleExpression:
    Description: Expression for scheduled execution (See https://docs.aws.amazon.com/eventbridge/latest/userguide/scheduled-events.html)
    Type: String
    Default: rate(1 hour)
  SearchRadius:
    Type: String
    Description: Search radius for stores in a specified location (in miles)
    Default: '50'
  State:
    Type: String
    Description: US State
  TopicName:
    Type: String
    Description: SNS Topic Name
    Default: covid-19-vaccine-notifications
  ZipCode:
    Type: String
    Description: US Zip Code
Resources:
  Covid19VaccineNotifier:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: 'Notifies for COVID-19 vaccine availability'
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref SnsTopic
      Events:
        ScheduledExecution:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
      Environment:
        Variables:
          EXCLUDED_LOCATIONS: !Join [',', !Ref ExcludedLocations]
          SEARCH_RADIUS: !Ref SearchRadius
          SNS_TOPIC_ARN: !Ref SnsTopic
          STATE: !Ref State
          ZIP_CODE: !Ref ZipCode
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: COVID-19 Vaccine Notifier
      TopicName: !Ref TopicName
